### Server ###
server:
  port: 8080

### DB ###
spring.datasource:
     type: org.apache.commons.dbcp2.BasicDataSource
     username: root
     password: 123456
     url: jdbc:mysql://localhost:3306/rc?useSSL=false&allowMultiQueries=true
     # connect pool conf
     dbcp2:
       initial-size: 5
       max-total: 10
       min-idle: 5
       max-idle: 10
       max-wait-millis: 10000
       default-query-timeout: 180
       connection-properties: characterEncoding=utf8